framework:
  test: true
  translator: ~
  secret: '%env(APP_SECRET)%'
  #default_locale: en
  csrf_protection: true
  #http_method_override: true
  ide: 'phpstorm://open?url=file://%%f&line=%%l'
  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  #    session:
  #        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
  #        cookie_lifetime: 31536000
  #        gc_maxlifetime: 31536000
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    cookie_lifetime: 31536000
    gc_maxlifetime: 31536000
  templating: { engines: [ 'twig' ] }
  #esi: ~
  #fragments: ~
  php_errors:
    log: true

  cache: ~
#        default_redis_provider: 'redis://%redisHost%:6380'
#        app: cache.adapter.redis
#        system: cache.adapter.system

fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "nobody"
    sender_name: "nobody"
