security:
  role_hierarchy:
    ROLE_CUSTOMER: ROLE_USER
    ROLE_EMPLOYEE: ROLE_CUSTOMER
    ROLE_ADMIN: ROLE_EMPLOYEE
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    apiLogin:
      pattern: ^/api/login
      stateless: true
      anonymous: true
      json_login:
        check_path: api_login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: api
      stateless: true
      anonymous: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

    main:
      pattern: ^/
      user_checker: security.user_checker
      form_login:
        provider: fos_userbundle
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        success_handler: app.security.authentication_handler
        failure_handler: app.security.authentication_handler
      logout:
        path: fos_user_security_logout
        target: fos_user_security_login
        delete_cookies: [ 'PHPSESSID','BEARER' ]
      anonymous: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator


    # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/(%locales%)/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%' }
    - { path: ^/(%locales%)/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(REQUIRES_CHANNEL)%' }
    - { path: ^/(%locales%)/api/token/refresh, role: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: '%env(REQUIRES_CHANNEL)%' }

    - { path: ^/(%locales%)/api/mobile-function/check-vacation, role: ROLE_EMPLOYEE, requires_channel: '%env(REQUIRES_CHANNEL)%' }

    - { path: ^/(%locales%)/admin, role: ROLE_ADMIN , requires_channel: '%env(REQUIRES_CHANNEL)%'}
    - { path: ^/(%locales%)/api/mobile-function, role: ROLE_ADMIN, requires_channel: '%env(REQUIRES_CHANNEL)%' }

