web_profiler_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /{_locale}/_wdt
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%locales%'

web_profiler_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /{_locale}/_profiler
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%locales%'
