# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: '%env(LOCALE)%'
  locales: '%env(LOCALES)%'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'
  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  #    lexik_jwt_authentication.handler.authentication_success:
  #        public: true
  #        class: App\Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationSuccessHandler
  #        arguments:
  #            - "@lexik_jwt_authentication.jwt_manager"
  #            - "@event_dispatcher"
  #            - [ ]
  #            - true

  #    Redis:
  #        # you can also use \RedisArray, \RedisCluster or \Predis\Client classes
  #        class: Redis
  #        calls:
  #            - connect:
  #                  - '%env(REDIS_HOST)%'
  #                  - '%env(int:REDIS_PORT)%'

  #    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
  #        arguments:
  #            - '@Redis'
  #            - { 'prefix': 'safecloudsoft_api_session', 'ttl': 86400 }
  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - '%env(DATABASE_URL)%'
  App\EventListener\LoginListener:
    tags:
      - { name: 'kernel.event_listener', event: 'security.interactive_login' }
  security.logout.handler.session:
    class: App\EventListener\SessionLogoutHandler
    arguments:
      - "@fos_user.user_manager"
      - "@doctrine.orm.entity_manager"
      - "@SessionHandlerInterface"
  app.security.authentication_handler:
    class: App\Service\AuthenticationHandler
    public: false
    arguments:
      - "@router"
      - "@session"
      - "@lexik_jwt_authentication.jwt_manager"

  app.service.image_processor:
    class: App\Service\ImageProcessor
    arguments:
      - '@service_container'


  #TODO: BİR GRAPHQL INPUT OLUŞTURMA -----------------BAŞLANGIÇ---------------------------------------------------------------------

  App\GraphQL\InputType\InputGedmoTestLangType:
    tags:
      - { name: api_platform.graphql.type }
    arguments:
      - "@translator"

#TODO: BİR GRAPHQL INPUT OLUŞTURMA -----------------BİTİŞ---------------------------------------------------------------------
